/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Aula;
import modelo.SQLAula;

/**
 *
 * @author Sigriid
 */
public class AltaAula extends javax.swing.JFrame {

    /**
     * Creates new form AltaAula
     */
    public AltaAula() {
        initComponents();
        
        //Declarem variables per escollir tipus objectiu         
        SeleccioHorari.addItem("Matí");
        SeleccioHorari.addItem("Migdia");
        SeleccioHorari.addItem("Tarda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titol = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        disponi = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        SeleccioHorari = new javax.swing.JComboBox<>();
        btTornar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titol.setText("Alta d'aules per disponibilitat ");

        nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nom.setText("Nom d'aula:");

        disponi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        disponi.setText("Disponibilitat d'horari:");

        btTornar.setBackground(new java.awt.Color(153, 153, 153));
        btTornar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTornar.setText("Tornar");
        btTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTornarActionPerformed(evt);
            }
        });

        btGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(titol))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(disponi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nom)
                                .addGap(81, 81, 81)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SeleccioHorari, 0, 114, Short.MAX_VALUE)
                            .addComponent(txtNom)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btGuardar)
                            .addComponent(btTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titol)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disponi)
                    .addComponent(SeleccioHorari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btTornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGuardar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTornarActionPerformed
        //Funció del botó tornar, per retornar a la pantalla anterior sense tancar el programa:
        this.setVisible(false);
        Panel panel = new Panel();
        panel.setVisible(true);
    }//GEN-LAST:event_btTornarActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        //configuració botó guardar aula
        SQLAula modSql = new SQLAula();
        Aula mod = new Aula();
        
        //revisem que no estigui cap camp buit
        if (txtNom.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hi han valors buits, omple tota la informació");
        } else {

            //declarem variable de la selecció del tipus d'horari de disponibilitat d'aula
            String TipusHorari = (String) SeleccioHorari.getSelectedItem();

            //Segons selecció d'horari
            if (TipusHorari.equals("Matí")) {
                mod.setId_tipus(1); // si selecció és matí
            } else {
                mod.setId_tipus(3); //Sino és tarda          
            }
           
            mod.setNom(txtNom.getText());
            
            //si les dades corresponen amb els valors que es demana registre ok
            if (modSql.Registrar(mod)) {
                JOptionPane.showMessageDialog(null, "Registre correcte");
                Buidar();
                
            } else {
                    JOptionPane.showMessageDialog(null, "Aula ja existeix");
                    
                        
            }
        }

    }//GEN-LAST:event_btGuardarActionPerformed

    
    //buidem capses d'opcions 
    public void Buidar() {        
        txtNom.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SeleccioHorari;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btTornar;
    private javax.swing.JLabel disponi;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel titol;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
