/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.SQLObjectiu;

/**
 *
 * @author Sigriid
 */
public class LlistaObjectiu extends javax.swing.JFrame {
    
    private final SQLObjectiu SQLO;

    /**
     * Creates new form LlistaObjectiu
     */
    public LlistaObjectiu() {
        initComponents();
        SQLO =new SQLObjectiu();
        Llistar();        
        this.setLocationRelativeTo(null);
    }
    
    //creem mètode per llistar
    private void Llistar(){
        taulaObjectius.setModel(SQLO.GetDades());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titol = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btTornar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SelecObj = new javax.swing.JComboBox<>();
        btFiltrar = new javax.swing.JButton();
        TipusVariable = new javax.swing.JComboBox<>();
        textFiltre = new javax.swing.JLabel();
        botEliminar = new javax.swing.JButton();
        textFiltr = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taulaObjectius = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titol.setText("Llistat d'objectius GIM-IOC");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/logo ioc mini.png"))); // NOI18N

        btTornar.setBackground(new java.awt.Color(153, 153, 153));
        btTornar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTornar.setText("Tornar");
        btTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTornarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seleccionar tipus d'objectiu");

        SelecObj.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rutina", "Gimnàs", "Passos" }));

        btFiltrar.setBackground(new java.awt.Color(153, 153, 153));
        btFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btFiltrar.setText("Llistar objectius filtrats");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        TipusVariable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tipus d'objectiu" }));
        TipusVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipusVariableActionPerformed(evt);
            }
        });

        botEliminar.setBackground(new java.awt.Color(153, 153, 153));
        botEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botEliminar.setText("Esborrar objectiu");
        botEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarActionPerformed(evt);
            }
        });

        textFiltr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFiltrKeyReleased(evt);
            }
        });

        taulaObjectius.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(taulaObjectius);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titol)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SelecObj, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TipusVariable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFiltre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textFiltr)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btTornar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titol)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelecObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFiltrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TipusVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFiltr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFiltre, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(34, 34, 34)
                .addComponent(btTornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTornarActionPerformed
        //Funció del botó tornar, per retornar a la pantalla anterior sense tancar el programa:
        this.setVisible(false);
        PanelUser panelu = new PanelUser();
        panelu.setVisible(true);
    }//GEN-LAST:event_btTornarActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        //filtrar objectius per selecció de tipus
        taulaObjectius.setModel(SQLO.GetDada(SelecObj.getSelectedIndex()));
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void botEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarActionPerformed
        //acció al clicar al botó esborrar per esborrar l'objectiu seleccionat
        //creem variable
        int fila =taulaObjectius.getSelectedRowCount();
        
        //verifiquem si ha alguna fila seleccionada o no
        if (fila < 1){
            //Mostrem missatge d'avís conforme cal seleccionar una fila
            JOptionPane.showMessageDialog(null, "Selecciona un registre de la taula");
                    
        }else{
            //Si ja està seleccionat cridem el mètode per esborrar objectius
            SQLO.deleteObjectiu(taulaObjectius.getValueAt(taulaObjectius.getSelectedRow(), 0).toString());            
            
        }
    }//GEN-LAST:event_botEliminarActionPerformed

    private void textFiltrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFiltrKeyReleased
        //esdeveniment al pitjar la tecla enter
        char tecla = evt.getKeyChar();
        //verifiquem si la tecla pitjada és enter
        if (tecla == KeyEvent.VK_ENTER){
            taulaObjectius.setModel(SQLO.GetDadaFiltre(TipusVariable.getSelectedIndex(),textFiltr.getText()));
        }
    }//GEN-LAST:event_textFiltrKeyReleased

    private void TipusVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipusVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipusVariableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlistaObjectiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlistaObjectiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlistaObjectiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlistaObjectiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlistaObjectiu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelecObj;
    private javax.swing.JComboBox<String> TipusVariable;
    private javax.swing.JButton botEliminar;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btTornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    private javax.swing.JTable taulaObjectius;
    private javax.swing.JTextField textFiltr;
    private javax.swing.JLabel textFiltre;
    private javax.swing.JLabel titol;
    // End of variables declaration//GEN-END:variables
}
