/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import modelo.SQLUsuari;
import modelo.Usuari;



/**
 *
 * @author Sigriid
 */
public class LlistaUsuari extends javax.swing.JFrame {
    
    private final SQLUsuari SQLU;

    /**
     * Creates new form LlistaUsuaris
     */
    public LlistaUsuari() {
        initComponents();
        SQLU =new SQLUsuari();
        Llistar();        
        this.setLocationRelativeTo(null);
               
        
    }
    
    //creem mètode per llistar
    private void Llistar(){
        taulaUsers.setModel(SQLU.GetDades());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taulaUsers = new javax.swing.JTable();
        TITOL = new javax.swing.JLabel();
        LogoIoc = new javax.swing.JLabel();
        SelecUser = new javax.swing.JComboBox<>();
        textTipus = new javax.swing.JLabel();
        btFiltrar = new javax.swing.JButton();
        botEliminar = new javax.swing.JButton();
        btTornar = new javax.swing.JButton();
        TipusVariable = new javax.swing.JComboBox<>();
        textFiltr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        taulaUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taulaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(taulaUsers);

        TITOL.setBackground(new java.awt.Color(153, 153, 153));
        TITOL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TITOL.setText("Llista d'usuaris GIM-IOC");

        LogoIoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/logo ioc mini.png"))); // NOI18N

        SelecUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Usuari", "Profe" }));
        SelecUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecUserActionPerformed(evt);
            }
        });

        textTipus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textTipus.setText("Seleccionar tipus d'usuari");

        btFiltrar.setBackground(new java.awt.Color(153, 153, 153));
        btFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btFiltrar.setText("Llistar usuaris filtrats");
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        botEliminar.setBackground(new java.awt.Color(153, 153, 153));
        botEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botEliminar.setText("Esborrar usuari");
        botEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarActionPerformed(evt);
            }
        });

        btTornar.setBackground(new java.awt.Color(153, 153, 153));
        btTornar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTornar.setText("Tornar");
        btTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTornarActionPerformed(evt);
            }
        });

        TipusVariable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nom" }));
        TipusVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipusVariableActionPerformed(evt);
            }
        });

        textFiltr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFiltrKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTornar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoIoc)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTipus)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SelecUser, 0, 110, Short.MAX_VALUE)
                                    .addComponent(TipusVariable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(textFiltr)))
                            .addComponent(TITOL))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoIoc)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TITOL)
                        .addGap(35, 35, 35)
                        .addComponent(textTipus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelecUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFiltrar))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipusVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFiltr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btTornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
      
//filtrar usuaris per selecció de tipus
        taulaUsers.setModel(SQLU.GetDada(SelecUser.getSelectedIndex()));
        
        
    }//GEN-LAST:event_btFiltrarActionPerformed
    
    //acció al clicar al botó esborrar per esborrar l'usuari
    private void botEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarActionPerformed
        //creem variable
        int fila =taulaUsers.getSelectedRowCount();
        
        //verifiquem si ha alguna fila seleccionada o no
        if (fila < 1){
            //Mostrem missatge d'avís conforme cal seleccionar una fila
            JOptionPane.showMessageDialog(null, "Selecciona un registre de la taula");
                    
        }else{
            //Si ja està seleccionat cridem el mètode per esborrar usuaris
            SQLU.deleteUser(taulaUsers.getValueAt(taulaUsers.getSelectedRow(), 0).toString());            
            
        }            
        
    }//GEN-LAST:event_botEliminarActionPerformed

    private void btTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTornarActionPerformed
     //Funció del botó tornar, per retornar a la pantalla anterior sense tancar el programa:
        this.setVisible(false);
        Panel panel = new Panel();
        panel.setVisible(true);
    
    }//GEN-LAST:event_btTornarActionPerformed

    private void SelecUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelecUserActionPerformed

    private void TipusVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipusVariableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipusVariableActionPerformed

    private void textFiltrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFiltrKeyReleased
        //esdeveniment al pitjar la tecla enter
        char tecla = evt.getKeyChar();
        //verifiquem si la tecla pitjada és enter
        if (tecla == KeyEvent.VK_ENTER){
            taulaUsers.setModel(SQLU.GetDadaFiltre(TipusVariable.getSelectedIndex(),textFiltr.getText()));
        }
    }//GEN-LAST:event_textFiltrKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LlistaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LlistaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LlistaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LlistaUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LlistaUsuari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoIoc;
    private javax.swing.JComboBox<String> SelecUser;
    private javax.swing.JLabel TITOL;
    private javax.swing.JComboBox<String> TipusVariable;
    private javax.swing.JButton botEliminar;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btTornar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taulaUsers;
    private javax.swing.JTextField textFiltr;
    private javax.swing.JLabel textTipus;
    // End of variables declaration//GEN-END:variables
}
