/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Hash;
import modelo.SQLUsuaris;
import modelo.usuaris;

/**
 *
 * @author Sigriid
 */
public class RegistreAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Registre
     */
    public RegistreAdmin() {
        initComponents();

        //Declarem variables per escollir tipus usuari si Admin o Profe         
        SeleccioAdmin.addItem("Admin");
        SeleccioAdmin.addItem("Profe");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titol = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Usuari = new javax.swing.JLabel();
        txtUsuari = new javax.swing.JTextField();
        Contrasenya = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        ConfContrasenya = new javax.swing.JLabel();
        txtConfirmaPass = new javax.swing.JPasswordField();
        Nom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        Correu = new javax.swing.JLabel();
        txtCorreu = new javax.swing.JTextField();
        btRegistrar = new javax.swing.JButton();
        BtTornar = new javax.swing.JButton();
        SeleccioAdmin = new javax.swing.JComboBox<>();
        tipusUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Titol.setText("Registre Administradors GIM-IOC");

        Usuari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Usuari.setText("Usuari:");

        Contrasenya.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Contrasenya.setText("Contrasenya:");

        ConfContrasenya.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfContrasenya.setText("<html>Confirmar contrasenya:</html>");

        Nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nom.setText("Nom:");

        Correu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Correu.setText("Correu:");

        btRegistrar.setBackground(new java.awt.Color(153, 153, 153));
        btRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btRegistrar.setText("Registre");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        BtTornar.setBackground(new java.awt.Color(153, 153, 153));
        BtTornar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtTornar.setText("Tornar");
        BtTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTornarActionPerformed(evt);
            }
        });

        tipusUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipusUser.setText("Tipus usuari:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2)
                .addGap(0, 286, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Correu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contrasenya))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Usuari)
                            .addComponent(Nom)
                            .addComponent(tipusUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCorreu, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtNom)
                            .addComponent(txtConfirmaPass)
                            .addComponent(txtUsuari, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeleccioAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titol)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(BtTornar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titol)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuari)
                    .addComponent(txtUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contrasenya)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correu)
                    .addComponent(txtCorreu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipusUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegistrar)
                    .addComponent(BtTornar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        //configuració botó registre administradors
        SQLUsuaris modSql = new SQLUsuaris();
        usuaris mod = new usuaris();

        //declarem les variables per recollir la contrasenya i la confirmació
        String pass = new String(txtPass.getPassword());
        String passCon = new String(txtConfirmaPass.getPassword());

        //revisem que no estigui cap camp buit
        if (txtUsuari.getText().equals("") || pass.equals("") || passCon.equals("") || txtNom.getText().equals("") || txtCorreu.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hi han valors buits, omple tota la informació");
        } else {

            //declarem variable de la selecció del tipus d'administrador
            String TipusAdmin = (String) SeleccioAdmin.getSelectedItem();

            //Segons selecció d'usuari
            if (TipusAdmin.equals("Admin")) {
                mod.setId_tipus(1); // si selecció és Administrador és tipus usuari administrador
            } else {
                mod.setId_tipus(3); //Sino és tipus usuari professor           
            }

            if (pass.equals(passCon)) {
                if (modSql.ExisteixUsuari(txtUsuari.getText()) == 0) {

                    //verifiquem que el valor del camp de correu correspongui a un correu electrònic
                    if (modSql.EsEmail(txtCorreu.getText())) {

                        String newPass = Hash.sha1(pass);
                        mod.setUsuari(txtUsuari.getText());
                        mod.setPassword(newPass);
                        mod.setNom(txtNom.getText());
                        mod.setCorreu(txtCorreu.getText());

                        //si les dades corresponen amb els valors que es demana registre ok
                        if (modSql.Registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registre correcte");
                            Buidar();

                            //si les dades no corresponen amb els valors demanats, missatge error
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar les dades");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El correu no és vàlid");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Usuari ja existeix");
                }

                //si la contrasenya i la de confirmació no són iguals mostrem missatge d'avís
            } else {
                JOptionPane.showMessageDialog(null, "Les contrasenyes no coincideixen");
            }
        }


    }//GEN-LAST:event_btRegistrarActionPerformed

    //buidem capses d'opcions 
    public void Buidar() {
        txtUsuari.setText("");
        txtPass.setText("");
        txtConfirmaPass.setText("");
        txtNom.setText("");
        txtCorreu.setText("");
    }

    private void BtTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTornarActionPerformed
        //Funció del botó tornar, per retornar a la pantalla anterior sense tancar el programa:
        this.setVisible(false);
        Inici inici = new Inici();
        inici.setVisible(true);
    }//GEN-LAST:event_BtTornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistreAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtTornar;
    private javax.swing.JLabel ConfContrasenya;
    private javax.swing.JLabel Contrasenya;
    private javax.swing.JLabel Correu;
    private javax.swing.JLabel Nom;
    private javax.swing.JComboBox<String> SeleccioAdmin;
    private javax.swing.JLabel Titol;
    private javax.swing.JLabel Usuari;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel tipusUser;
    private javax.swing.JPasswordField txtConfirmaPass;
    private javax.swing.JTextField txtCorreu;
    private javax.swing.JTextField txtNom;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuari;
    // End of variables declaration//GEN-END:variables
}
